import type { Metadata } from "next";
import { DM_Sans } from "next/font/google"
import "../styles/globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";

export const font = DM_Sans({ subsets: ['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("min-h-screen bg-white antialiased", font.className)}
      >
        <Navbar />
        <main className="">
          {children}
        </main>
      </body>
    </html>
  );
}
